# Generated by Django 3.0.6 on 2020-05-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageUpload', '0003_auto_20200514_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageuploadmodel',
            name='image1',
            field=models.ImageField(default='', upload_to='images/Mona_Lisa'),
        ),
        migrations.AlterField(
            model_name='imageuploadmodel',
            name='image2',
            field=models.ImageField(default='', upload_to='images/Constructivism'),
        ),
    ]
