# Generated by Django 3.0.6 on 2020-05-14 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageUpload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageuploadmodel',
            name='name',
        ),
    ]
