# Generated by Django 3.0.6 on 2020-05-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageUpload', '0002_remove_imageuploadmodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageuploadmodel',
            name='image',
        ),
        migrations.AddField(
            model_name='imageuploadmodel',
            name='image1',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='imageuploadmodel',
            name='image2',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
